"""pinned document fk set null on delete

Revision ID: 6e11010967fb
Revises: f5b8758cf2fa
Create Date: 2026-09-09 20:08:34.860010

"""
from typing import Sequence, Union

from alembic import op


revision: str = '6e11010967fb'
down_revision: Union[str, None] = 'f5b8758cf2fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chat_sessions_pinned_document_id_fkey', 'chat_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'chat_sessions', 'documents', ['pinned_document_id'], ['id'], referent_schema='kb', ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_sessions', type_='foreignkey')
    op.create_foreign_key('chat_sessions_pinned_document_id_fkey', 'chat_sessions', 'documents', ['pinned_document_id'], ['id'], referent_schema='kb')
    # ### end Alembic commands ###
