"""add agents and alerts

Revision ID: f5b8758cf2fa
Revises: 28a896b34391
Create Date: 2026-09-09 14:07:44.557877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'f5b8758cf2fa'
down_revision: Union[str, None] = '28a896b34391'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('trigger_type', sa.String(length=20), nullable=False),
    sa.Column('webhook_path', sa.String(length=255), nullable=False),
    sa.Column('triage_prompt', sa.Text(), nullable=False),
    sa.Column('severity_rule', sa.Text(), nullable=False),
    sa.Column('auto_remediation_enabled', sa.Boolean(), nullable=False),
    sa.Column('group_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_triaged', sa.Integer(), nullable=False),
    sa.Column('real_issues_detected', sa.Integer(), nullable=False),
    sa.Column('noise_filtered_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('agent_name', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('verdict', sa.String(length=20), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('labels', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('annotations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('canary_name', sa.String(length=255), nullable=True),
    sa.Column('canary_start_url', sa.String(length=500), nullable=True),
    sa.Column('canary_end_url', sa.String(length=500), nullable=True),
    sa.Column('canary_error_step', sa.String(length=255), nullable=True),
    sa.Column('canary_error_msg', sa.Text(), nullable=True),
    sa.Column('canary_steps', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('runbook_link', sa.String(length=500), nullable=True),
    sa.Column('triage_report', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('group_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alerts')
    op.drop_table('agents')
    # ### end Alembic commands ###
